- name: install mysql
  yum: pkg={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-devel
    - MySQL-python

- name: chkconfig mysqld on
  service: name=mysqld state=started enabled=yes

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: delete anonymous mysql server user for localhost
  mysql_user: user="" state="absent"

- name: remove the mysql test database
  mysql_db: db=test state=absent

- name: add gitlab database
  mysql_db: db=gitlabhq_production state=present encoding=utf8 collation=utf8_unicode_ci

- name: add user for gitlab database
  mysql_user: user=git host=localhost password={{ mysql_git_password }} state=present
              priv="gitlabhq_production.*:SELECT, LOCK TABLES, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER"
